### ISSUE TITLE
4. Create application form

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#138]
### Background

Having identified the criteria for the role, we need to create a form that allows candidates to apply and confirm that they meet all those criteria with minimum need for manual check. We also need to collect examples of work to help us choose between candidates.

Example application with security clearance form (https://docs.google.com/forms/d/e/1FAIpQLSex5f4LvEXlKjEC8LvsKhSm6SdR1USpd8eNesjM-YFPsM1ymw/viewform?usp=sharing)

### Acceptance criteria

- [x] Form is located in the correct folder see - #137 
- [x]  Form captures all identified criteria from - #136  
- [x]  Form includes any restrictions identified on #136 
- [x]  Form requests links to Live Demos & Repos Portfolio (which should include projects)
- [x]  Form asks for any other information needed (i.e. relevant experience)
- [x]  Form has open questions for additional information from applicants

### Owner

@barny-6

### Stakeholder

@barny-6

### Approver

@barny-6

**Comment by Barny-6** [comment]
https://docs.google.com/forms/d/1Znqtx9Zwons7cU5bE1AAyxlAZHwaR3PvsbYJeZfXzTE/edit
