### ISSUE TITLE
Set up regular job openings tracking

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#58]
**Background**
We need to have a finger on the pulse of what jobs are available. This can be done both through finding a scraper that compiles job opening numbers and manual checking. 

**Acceptance Criteria**
- [x] Regular calendar slot to do manual checks
- [x] Confirm search criteria for manual check to maintain consistency in numbers
- [x] Book time to search for a compiler (and link to second ticket

**Owner**
@Barny-6 

**Approver**
@Barny-6
