### ISSUE TITLE
Add Portfolios on to tracker

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#68]
### Background

The [grad tracker ](https://docs.google.com/spreadsheets/d/1FNA-eLB03n4okAEGp3u1wiWs2Ee5RqTZb0MnOeeU70o/edit#gid=0)would be more powerful if it had links to all the grads portfolio pages (see portfolio of portfolios on slack)

### Acceptance criteria

- [x] Portfolio space on grad tracker
- [x] all prtofolios on the slack canvas added to track
- [x] other grads asked for portfolios

### Owner

@barny-6

### Stakeholder

@barny-6

### Approver

@barny-6
