### ISSUE TITLE
5. Create application form for CIS role

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#85]
### Background

Having identified the criteria for the role, we need to create a form that allows candidates to apply and confirm that they meet all those criteria with minimum need for manual check. We also need to collect examples of work to help us choose between candidates. 

Example application with security clearance form (https://docs.google.com/forms/d/e/1FAIpQLSex5f4LvEXlKjEC8LvsKhSm6SdR1USpd8eNesjM-YFPsM1ymw/viewform?usp=sharing)

### Acceptance criteria

- [x] Form is located in the correct folder see - https://github.com/CodeYourFuture/Barny/issues/84
- [x] Form captures all identified criteria from https://github.com/CodeYourFuture/Barny/issues/83
- [x]  Form includes any restrictions identified on https://github.com/CodeYourFuture/Barny/issues/83
- [x]  Form requests links to Live Demos & Repos Portfolio (which should include projects)
- [x]  Form asks for any other information needed (i.e. relevant experience)
- [x] Form has open question for additional information from applicants

### Owner

@barny-6

### Stakeholder

@barny-6

### Approver

@barny-6

**Comment by Barny-6** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSfVLs_BdMKnTLHUGuUcoLT8wrrTfCcUQ-TDYkC_yc5At9O_Mw/viewform?usp=sf_link
